### ISSUE TITLE
Remove unused console.log

### ISSUE THREAD

**Issue by LasaleFamine** [super-cache-money/make-runnable#2]
I have been struggle 20 min to understand that the `undefined` in my console was related to `make-runnable`.

```bash 
$ node build.js vulcanize
running func []
undefined
BUILD.JS: Everithing done!  
✨  Done in 23.70s.
```

I think could be good specify when the `console.log` is printed from the `make-runnable` script and maybe could be also good to add a flag like `-v` (verbose) to enable the logger within `make-runnable`

I can come back with a PR if you agree.

**Comment by super-cache-money** [comment]
You are totally right. I'll get to fixing that. Sorry about your 20 minutes!

**Comment by LasaleFamine** [comment]
Not a real problem my 20 minutes :D 
Thank you for the module instead!

**Comment by super-cache-money** [comment]
All done :)

**Comment by super-cache-money** [comment]
There's a need to print out the output of the called function. To stop it from being confusing, it now prints output of a function like this:
```
--------make-runnable-output--------
OUTPUT!!!
------------------------------------
```
