### ISSUE TITLE
Add option to hide `--------make-runnable-output--------`

### ISSUE THREAD

**Issue by tech4him1** [super-cache-money/make-runnable#3]
Can you add an option to change or hide the `--------make-runnable-output--------` and `--------make-runnable-errors--------` headers?

**Comment by super-cache-money** [comment]
Hi, sure, I can do that. I'll get around to it as soon as I can. If you're in a rush, feel free to send in a PR :)

**Comment by super-cache-money** [comment]
Any suggestions for how you'd expect to specify this option? maybe as a --flag?

**Comment by tech4him1** [comment]
I can make a PR if you want.

I was wanting it as an option for the developer, not for the user, so I was thinking something like
```js
require('make-runnable')({
    wrapOutput: false
});
```
or
```js
require('make-runnable')({
    wrapOutput: ['----------my-app-name----------',  '------------------------------------']
});
```

**Comment by pinussilvestrus** [comment]
+1

**Comment by super-cache-money** [comment]
@tech4him1 I'd accept that 🔥

**Comment by robinjoseph08** [comment]
@tech4him1 looks like you have a branch for it. Will you be putting up a PR? If not, I can do it as well.

**Comment by tech4him1** [comment]
@robinjoseph08 either way, I am fairly busty right now, so if you want to, you can go ahead.

**Comment by tech4him1** [comment]
This seems to be a little harder than it looks. If I wrap the whole script like this:
```js
module.exports = function(options) {
   // Everything else goes here.
}
```
that works, but breaks backward compatibility. Everybody from now on would have to do `require('make-runnable')({})` instead of just `require('make-runnable')`. Do you have any better way to do it?

**Comment by super-cache-money** [comment]
@tech4him1 it is (was :D) a bit of a hairy problem but I think what I've added addresses it...
https://github.com/super-cache-money/make-runnable/commit/3fff42d9531da6051a104a8cd34e7b8ae0e868cf
You can now do:
```
require('make-runnable/custom')({
    printOutputFrame: false
})
```

**Comment by tech4him1** [comment]
Looks awesome!
